#services:
#  mysql:
#    image: mysql
#    ports:
#      - "3306:3306"
#    expose:
#      - "3306"
#    environment:
#      - MYSQL_USER=springuser
#      - MYSQL_PASSWORD=ThePassword
#      - MYSQL_DATABASE=db_example
#      - MYSQL_ROOT_PASSWORD=root
#    volumes:
#      - "./conf.d:/etc/mysql/conf.d:ro"

version: '3.1'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: ThePassword
      POSTGRES_DB: db_example
    ports:
      - "5432:5432"
